# This is a basic workflow to help you get started with Actions on CMSIS projects
# See also https://community.arm.com/developer/tools-software/tools/b/tools-software-ides-blog/posts/infrastructure-for-continuous-integration-tests
#
# The repository needs to provide the following secrets
# - AWS_ACCESS_KEY_ID           The id of the access key.
# - AWS_SECRET_ACCESS_KEY       The access key secret.
# - AWS_DEFAULT_REGION          The data center region to be used.
# - AWS_S3_BUCKET_NAME          The name of the S3 storage bucket to be used for data exchange.
# - AWS_IAM_PROFILE             The IAM profile to be used.
# - AWS_SECURITY_GROUP_ID       The id of the security group to add the EC2 instance to.
# - AWS_SUBNET_ID               The id of the network subnet to connect the EC2 instance to.
# - ARM_UBL                     A bzip2 compressed and base64-encoded user based license file:
#                               armlm activate --server <URL> --product <PRODUCT> --as-user ubuntu --to-file ubuntu-ubl.binlic
#                               bzip2 -c ubuntu-ubl.binlic | base64 > ubuntu-ubl.binlic.bz2.b64

name: Arm Virtual Hardware Blinky example - github hosted - remote AWS via GH plugin
on:
  push:
    branches: [ main ]
  pull_request:
    paths:
      - .github/workflows/blinky.yml
      - Blinky_Cortex-M85/**/*
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
  AWS_IAM_PROFILE: ${{ secrets.AWS_IAM_PROFILE }}
  AWS_SECURITY_GROUP_ID: ${{ secrets.AWS_SECURITY_GROUP_ID }}
  AWS_SUBNET_ID: ${{ secrets.AWS_SUBNET_ID }}
  ARM_UBL: ${{ secrets.ARM_UBL }}
jobs:
  ci_test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install AVH Client for Python
      run: |
        pip install git+https://github.com/ARM-software/avhclient.git@latest

    - uses: ammaraskar/gcc-problem-matcher@master

    - name: Run tests
      id: avh
      run: |
        printenv ARM_UBL | base64 -d | bunzip2 > Blinky_Cortex-M85/ubuntu-ubl.binlic
        avhclient -b aws execute --specfile Blinky_Cortex-M85/avh.yml
        count=$(grep -c "LED" Blinky_Cortex-M85/vht.log)
        echo "Found 'LED' ${count} times in vht.log ..."
        if [[ $count < 19 ]]; then
          echo "... this is less than the expected 19 times!"
          exit 1
        fi

    - name: Archive results
      uses: actions/upload-artifact@v2
      with:
        name: results
        path: |
          Blinky_Cortex-M85/Objects/Blinky.axf
          Blinky_Cortex-M85/Objects/Blinky.axf.map
          Blinky_Cortex-M85/EventRecorder.log
          Blinky_Cortex-M85/vht.log
        retention-days: 1
        if-no-files-found: error
      if: always()
